# Installing libraries

In [1]:
!pip install vecstack

  Preparing metadata (setup.py) ... done
  Created wheel for vecstack: filename=vecstack-0.4.0-py3-none-any.whl size=19863 sha256=520baf3c52585b1b25e54cf4c90b7d8e083ee2de97fe5913ab99ee8edd91ff20
  Stored in directory: /root/.cache/pip/wheels/b8/d8/51/3cf39adf22c522b0a91dc2208db4e9de4d2d9d171683596220
Successfully built vecstack


# Importing libraries

In [ ]:

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import RandomizedSearchCV

from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, log_loss


from imblearn.over_sampling import SMOTE

from collections import Counter

from vecstack import stacking


# Reading Kaggle Datasets

In [ ]:
# reading the kaggle training dataset

train_data = pd.read_csv("RevisedHomesiteTrain1.csv")
train_data

CoverageField11A  CoverageField11B  CoverageField1A  CoverageField1B  \
0                     2                 1               17               23   
1                     5                 9                6                8   
2                     4                 6                7               12   
3                    15                23                3                2   
4                     4                 6                8               13   
...                 ...               ...              ...              ...   
64995                 3                 5                9               15   
64996                 5                 9               14               21   
64997                 7                14                3                2   
64998                 5                 9               15               22   
64999                 4                 6                7               12   

       CoverageField2A  CoverageField2B  CoverageField3A  CoverageField3B  \
0                   17               23               15               22   
1                    6                8                5                7   
2                    7               12                6               10   
3                    3                2                2                2   
4                    8               13                7               11   
...                ...              ...              ...              ...   
64995                9               15                8               13   
64996               14               21               13               20   
64997                3                3                2                2   
64998               15               22               13               21   
64999                8               13                7               11   

       CoverageField4A  CoverageField4B  ...  PropertyField38_N  \
0                   16               22  ...                  1   
1                    5                8  ...                  1   
2                    7               11  ...                  1   
3                    3                2  ...                  1   
4                    7               13  ...                  1   
...                ...              ...  ...                ...   
64995                8               14  ...                  1   
64996               13               21  ...                  1   
64997                3                2  ...                  1   
64998               14               21  ...                  1   
64999                7               12  ...                  1   

       PropertyField38_Y  GeographicField63_   GeographicField63_N  \
0                      0                    0                    1   
1                      0                    0                    1   
2                      0                    0                    1   
3                      0                    0                    1   
4                      0                    0                    1   
...                  ...                  ...                  ...   
64995                  0                    0                    1   
64996                  0                    0                    1   
64997                  0                    0                    1   
64998                  0                    0                    1   
64999                  0                    0                    1   

       GeographicField63_Y  GeographicField64_CA  GeographicField64_IL  \
0                        0                     1                     0   
1                        0                     0                     0   
2                        0                     0                     0   
3                        0                     0                     0   
4                        0                     0                     1   
...                    ...                 

In [ ]:
# reading the kaggle testing dataset

test_data = pd.read_csv("RevisedHomesiteTest1.csv")
test_data

CoverageField11A  CoverageField11B  CoverageField1A  CoverageField1B  \
0                     13                22                4                4   
1                      4                 5                8               14   
2                      3                 3               11               18   
3                      5                 9               14               22   
4                     12                21                4                5   
...                  ...               ...              ...              ...   
173831                14                23               13               21   
173832                 7                13               10               17   
173833                12                22                4                4   
173834                 6                11                4                5   
173835                 2                 2               16               23   

        CoverageField2A  CoverageField2B  CoverageField3A  CoverageField3B  \
0                     4                4                3                3   
1                     8               14                7               12   
2                    11               18               10               16   
3                    15               22               13               20   
4                     4                5                4                4   
...                 ...              ...              ...              ...   
173831               13               21               18               23   
173832               10               17                9               15   
173833                4                5                4                4   
173834                4                5                4                4   
173835               16               23               21               24   

        CoverageField4A  CoverageField4B  ...  PropertyField38_N  \
0                     3                4  ...                  1   
1                     8               13  ...                  1   
2                    10               18  ...                  1   
3                    22               25  ...                  1   
4                     4                5  ...                  1   
...                 ...              ...  ...                ...   
173831               13               20  ...                  0   
173832                9               16  ...                  1   
173833                4                4  ...                  1   
173834                4                4  ...                  1   
173835               15               22  ...                  1   

        PropertyField38_Y  GeographicField63_   GeographicField63_N  \
0                       0                    0                    0   
1                       0                    0                    1   
2                       0                    0                    1   
3                       0                    0                    1   
4                       0                    0                    1   
...                   ...                  ...                  ...   
173831                  1                    0                    1   
173832                  0                    0                    1   
173833                  0                    0                    1   
173834                  0                    0                    1   
173835                  0                    0                    1   

        GeographicField63_Y  GeographicField64_CA  GeographicField64_IL  \
0                         1                     0                     0   
1                         0                     0                     0   
2                         0                     0                     0   
3                         0                     0                     0   
4                         0                     0                

# Data Preprocessing

In [ ]:
# dropping the last column from the kaggle test dataset because that column is not present in the kaggle training dataset
test_data = test_data.drop('GeographicField64', axis=1)
test_data

CoverageField11A  CoverageField11B  CoverageField1A  CoverageField1B  \
0                     13                22                4                4   
1                      4                 5                8               14   
2                      3                 3               11               18   
3                      5                 9               14               22   
4                     12                21                4                5   
...                  ...               ...              ...              ...   
173831                14                23               13               21   
173832                 7                13               10               17   
173833                12                22                4                4   
173834                 6                11                4                5   
173835                 2                 2               16               23   

        CoverageField2A  CoverageField2B  CoverageField3A  CoverageField3B  \
0                     4                4                3                3   
1                     8               14                7               12   
2                    11               18               10               16   
3                    15               22               13               20   
4                     4                5                4                4   
...                 ...              ...              ...              ...   
173831               13               21               18               23   
173832               10               17                9               15   
173833                4                5                4                4   
173834                4                5                4                4   
173835               16               23               21               24   

        CoverageField4A  CoverageField4B  ...  PropertyField37_Y  \
0                     3                4  ...                  1   
1                     8               13  ...                  0   
2                    10               18  ...                  0   
3                    22               25  ...                  0   
4                     4                5  ...                  0   
...                 ...              ...  ...                ...   
173831               13               20  ...                  0   
173832                9               16  ...                  0   
173833                4                4  ...                  1   
173834                4                4  ...                  1   
173835               15               22  ...                  0   

        PropertyField38_N  PropertyField38_Y  GeographicField63_   \
0                       1                  0                    0   
1                       1                  0                    0   
2                       1                  0                    0   
3                       1                  0                    0   
4                       1                  0                    0   
...                   ...                ...                  ...   
173831                  0                  1                    0   
173832                  1                  0                    0   
173833                  1                  0                    0   
173834                  1                  0                    0   
173835                  1                  0                    0   

        GeographicField63_N  GeographicField63_Y  GeographicField64_CA  \
0                         0                    1                     0   
1                         1                    0                     0   
2                         1                    0                     0   
3                         1                    0                     0   
4                         1                    0                     0   
...                 

In [ ]:
train_data.info()

# dataset has all numerical type columns only

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65000 entries, 0 to 64999
Columns: 596 entries, CoverageField11A to QuoteConversion_Flag
dtypes: float64(5), int64(591)
memory usage: 295.6 MB


In [ ]:
train_data.describe()

CoverageField11A  CoverageField11B  CoverageField1A  CoverageField1B  \
count      65000.000000      65000.000000     65000.000000     65000.000000   
mean           7.798892         12.954892         9.014585        12.995831   
std            5.304856          7.259023         5.586114         7.217093   
min           -1.000000         -1.000000        -1.000000        -1.000000   
25%            4.000000          7.000000         5.000000         7.000000   
50%            6.000000         13.000000         8.000000        13.000000   
75%           10.000000         19.000000        12.000000        19.000000   
max           25.000000         25.000000        25.000000        25.000000   

       CoverageField2A  CoverageField2B  CoverageField3A  CoverageField3B  \
count     65000.000000     65000.000000     65000.000000     65000.000000   
mean          9.060000        13.017308         9.064538        13.017877   
std           5.568791         7.207118         5.588694         7.212825   
min           1.000000         1.000000         1.000000         1.000000   
25%           5.000000         7.000000         5.000000         7.000000   
50%           8.000000        13.000000         8.000000        13.000000   
75%          12.000000        19.000000        12.000000        19.000000   
max          25.000000        25.000000        25.000000        25.000000   

       CoverageField4A  CoverageField4B  ...  PropertyField38_N  \
count     65000.000000     65000.000000  ...       65000.000000   
mean          8.973785        13.011031  ...           0.974969   
std           5.564675         7.203325  ...           0.156220   
min           1.000000         1.000000  ...           0.000000   
25%           5.000000         7.000000  ...           1.000000   
50%           8.000000        13.000000  ...           1.000000   
75%          12.000000        19.000000  ...           1.000000   
max          25.000000        25.000000  ...           1.000000   

       PropertyField38_Y  GeographicField63_   GeographicField63_N  \
count       65000.000000              65000.0         65000.000000   
mean            0.020292                  0.0             0.976262   
std             0.140999                  0.0             0.152234   
min             0.000000                  0.0             0.000000   
25%             0.000000                  0.0             1.000000   
50%             0.000000                  0.0             1.000000   
75%             0.000000                  0.0             1.000000   
max             1.000000                  0.0             1.000000   

       GeographicField63_Y  GeographicField64_CA  GeographicField64_IL  \
count         65000.000000          65000.000000          65000.000000   
mean              0.023738              0.361862              0.120908   
std               0.152234              0.480543              0.326022   
min               0.000000              0.000000              0.000000   
25%               0.000000              0.000000              0.000000   
50%               0.000000              0.000000              0.000000   
75%               0.000000              1.000000              0.000000   
max               1.000000              1.000000              1.000000   

       GeographicField64_NJ  GeographicField64_TX  QuoteConversion_Flag  
count          65000.000000          65000.000000          65000.000000  
mean               0.267631              0.249600              0.188646  
std                0.442727              0.432785              0.391230  
min                0.000000              0.000000              0.000000  
25%                0.000000              0.000000              0.000000  
50%                0.000000              0.000000              0.000000  
75%                1.000000              0.000000              0.000000  
max                1.000000              1.000000              1.000000  

[8 rows x 596 columns]

In [ ]:
# checking if there are any missing values in the dataset
if 1 in train_data.isnull().sum().values:
  print("missing value")

# there are no missing values in the dataset

In [ ]:
train_data['QuoteConversion_Flag'].value_counts()

# dataset is imbalanced

0    52738
1    12262
Name: QuoteConversion_Flag, dtype: int64

In [ ]:
# Separating the input and output of the kaggle training dataset
X = train_data.iloc[:,:-1]
y = train_data['QuoteConversion_Flag']

In [ ]:
# creating new records belonging to the minority class using SMOTE. (performing oversampling to balance the dataset)
# making the number of minority class records equal to the majority class records
# 1 is the minority class and 0 is the majority class

print('Original dataset shape %s' % Counter(y))
sm = SMOTE(sampling_strategy={1: 52738})
X_res, y_res = sm.fit_resample(X, y)
print('Resampled dataset shape %s' % Counter(y_res))

Original dataset shape Counter({0: 52738, 1: 12262})
Resampled dataset shape Counter({0: 52738, 1: 52738})


In [ ]:
# splitting the kaggle training dataset into training and testing dataset to measure performance
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.3, random_state=42)

In [ ]:
# distribution of the class in the training dataset
y_train.value_counts()

1    36986
0    36847
Name: QuoteConversion_Flag, dtype: int64

# Building and Training models

## Neural Network - Multi layered perceptron

In [ ]:

mlp = MLPClassifier(max_iter = 100)
mlp.fit(X_train, y_train)
mlp_predict=mlp.predict(X_test)
print("accuracy Score (training) for MultiLayer Perceptron:{0:6f}".format(mlp.score(X_test,y_test)))
print("Confusion Matrix for MultiLayer Perceptron:")
print(confusion_matrix(y_test,mlp_predict))
print(classification_report(mlp_predict, y_test))


accuracy Score (training) for MultiLayer Perceptron:0.906899
Confusion Matrix for MultiLayer Perceptron:
[[14763  1128]
 [ 1818 13934]]
              precision    recall  f1-score   support

           0       0.93      0.89      0.91     16581
           1       0.88      0.93      0.90     15062

    accuracy                           0.91     31643
   macro avg       0.91      0.91      0.91     31643
weighted avg       0.91      0.91      0.91     31643



neural networks perform well with large datasets because of their deep architecture. it allows them to capture intricate patterns among a large number of features.

## SVC - Support Vector Classifier

In [ ]:
svm = SVC(max_iter = 500)
svm.fit(X_train, y_train)
svm_predict=svm.predict(X_test)
print("accuracy Score (training) for SVM Classifier:{0:6f}".format(svm.score(X_test,y_test)))
print("Confusion Matrix for SVM Classifier:")
print(confusion_matrix(y_test,svm_predict))
print(classification_report(svm_predict, y_test))

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


accuracy Score (training) for SVM Classifier:0.499795
Confusion Matrix for SVM Classifier:
[[9225 6666]
 [9162 6590]]
              precision    recall  f1-score   support

           0       0.58      0.50      0.54     18387
           1       0.42      0.50      0.45     13256

    accuracy                           0.50     31643
   macro avg       0.50      0.50      0.50     31643
weighted avg       0.51      0.50      0.50     31643



SVC performs classification by creating a hyperplane that separates out the points belonging to different classes. This hyperplane is represented by the equation wx+b where w is the weight, x is the vector and b is the bias. its goal is to maximize the margin between the classes and minimize classification error by computing the pairwise similarities between the data points or vectors.  The larger our dataset, i.e, the more number of vectors we have, the more computationally expensive it becomes. This is why SVM does not perform well on large datasets.

## Decision Tree

In [ ]:
clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)
clf_predict=clf.predict(X_test)
print("accuracy Score (training) for Decision Tree:{0:6f}".format(clf.score(X_test,y_test)))
print("Confusion Matrix for Decision Tree")
print(confusion_matrix(y_test,clf_predict))
print(classification_report(clf_predict, y_test))

accuracy Score (training) for Decision Tree:0.918813
Confusion Matrix for Decision Tree
[[14520  1371]
 [ 1198 14554]]
              precision    recall  f1-score   support

           0       0.91      0.92      0.92     15718
           1       0.92      0.91      0.92     15925

    accuracy                           0.92     31643
   macro avg       0.92      0.92      0.92     31643
weighted avg       0.92      0.92      0.92     31643



decision trees work well for large datasets with large number of features because decision trees inherently perform feature selection. They can understand which features are important and which are not. They can capture intricate patterns between the features as well

## Random Forest

In [ ]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
rfc_predict=rfc.predict(X_test)
print("accuracy Score (training) for RandomForest:{0:6f}".format(rfc.score(X_test,y_test)))
print("Confusion Matrix for Random Forest:")
print(confusion_matrix(y_test,rfc_predict))
print(classification_report(rfc_predict, y_test))

accuracy Score (training) for RandomForest:0.939513
Confusion Matrix for Random Forest:
[[15246   645]
 [ 1269 14483]]
              precision    recall  f1-score   support

           0       0.96      0.92      0.94     16515
           1       0.92      0.96      0.94     15128

    accuracy                           0.94     31643
   macro avg       0.94      0.94      0.94     31643
weighted avg       0.94      0.94      0.94     31643



Random forests work well because they create multiple decision trees and decrease the overall error rate. this is why random forests perform better than decision trees

## K nearest neighbors - KNN

In [ ]:
neigh = KNeighborsClassifier(n_neighbors=3)

neigh.fit(X_train, y_train)
neigh_predict=neigh.predict(X_test)
print("accuracy Score (training) for KNeighborsClassifier:{0:6f}".format(neigh.score(X_test,y_test)))
print("Confusion Matrix for KNeighborsClassifier:")
print(confusion_matrix(y_test,neigh_predict))
print(classification_report(neigh_predict, y_test))

accuracy Score (training) for KNeighborsClassifier:0.741554
Confusion Matrix for KNeighborsClassifier:
[[ 9862  6029]
 [ 2149 13603]]
              precision    recall  f1-score   support

           0       0.62      0.82      0.71     12011
           1       0.86      0.69      0.77     19632

    accuracy                           0.74     31643
   macro avg       0.74      0.76      0.74     31643
weighted avg       0.77      0.74      0.75     31643



KNN works by computing the similarity between the new data point and the rest of the data points in the dataset and classifying the new data point to the class which majority of the k nearest neighbors to the new data point belong to. Thus the training time increases linearly as the dataset increases, which increases the compuatational complexity. This why KNN does not work well with large datasets. Also, KNN does not work well when there are many features. The distance or the similarity between the data points are less meaningful when the number of features are very large. This leads to degraded performance.

## Stacking the models

In [ ]:
models = [ MLPClassifier(max_iter = 100), SVC(max_iter = 500), DecisionTreeClassifier(), RandomForestClassifier(), KNeighborsClassifier(n_neighbors=3)]

S_Train, S_Test = stacking(models,
                           X_train, y_train, X_test,
                           regression=False,

                           mode='oof_pred_bag',

                           needs_proba=False,

                           save_dir=None,

                           metric=accuracy_score,

                           n_folds=4,

                           stratified=True,

                           shuffle=True,

                           random_state=0,

                           verbose=2)

task:         [classification]
n_classes:    [2]
metric:       [accuracy_score]
mode:         [oof_pred_bag]
n_models:     [5]

model  0:     [MLPClassifier]
    fold  0:  [0.87550788]
    fold  1:  [0.90416080]
    fold  2:  [0.89018312]
    fold  3:  [0.64329830]
    ----
    MEAN:     [0.82828752] + [0.10728303]
    FULL:     [0.82828816]

model  1:     [SVC]


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


    fold  0:  [0.50327753]


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


    fold  1:  [0.49750786]


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


    fold  2:  [0.50189620]


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


    fold  3:  [0.50715137]
    ----
    MEAN:     [0.50245824] + [0.00344670]
    FULL:     [0.50245825]

model  2:     [DecisionTreeClassifier]
    fold  0:  [0.91749282]
    fold  1:  [0.91716329]
    fold  2:  [0.91694658]
    fold  3:  [0.91840936]
    ----
    MEAN:     [0.91750301] + [0.00055826]
    FULL:     [0.91750301]

model  3:     [RandomForestClassifier]
    fold  0:  [0.93867490]
    fold  1:  [0.93823816]
    fold  2:  [0.93699209]
    fold  3:  [0.93872576]
    ----
    MEAN:     [0.93815773] + [0.00069916]
    FULL:     [0.93815773]

model  4:     [KNeighborsClassifier]
    fold  0:  [0.72089496]
    fold  1:  [0.71979629]
    fold  2:  [0.71724997]
    fold  3:  [0.71681656]
    ----
    MEAN:     [0.71868945] + [0.00170801]
    FULL:     [0.71868947]



In [ ]:
np.savetxt("s_train.csv", S_Train, delimiter=",")


In [ ]:
np.savetxt("s_test.csv", S_Test, delimiter=",")

In [ ]:
S_Train

array([[1, 0, 0, 0, 1],
       [1, 0, 1, 1, 1],
       [0, 0, 0, 0, 0],
       ...,
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [ ]:
S_Test

array([[0, 0, 0, 0, 1],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1]])

In [ ]:
from numpy import genfromtxt
S_Train = genfromtxt('s_train.csv', delimiter=',')
S_Train

array([[1., 0., 0., 0., 1.],
       [1., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       ...,
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [ ]:
from numpy import genfromtxt
S_Test = genfromtxt('s_test.csv', delimiter=',')
S_Test

array([[0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

## Meta Model - MLP

In [ ]:
model = MLPClassifier(max_iter = 100)

model = model.fit(S_Train, y_train)
y_pred = model.predict(S_Test)
print('Final prediction score for ensemble methods: [%.8f]' % accuracy_score(y_test, y_pred))
print(classification_report(y_pred, y_test))

Final prediction score for ensemble methods: [0.94251493]
              precision    recall  f1-score   support

           0       0.98      0.92      0.94     16952
           1       0.91      0.97      0.94     14691

    accuracy                           0.94     31643
   macro avg       0.94      0.94      0.94     31643
weighted avg       0.94      0.94      0.94     31643



In [ ]:
#Hyperparameter tuning done for MultiLayer Perceptron classifier

parameters = {
              'activation':['logistic', 'relu'],
              'learning_rate':['constant', 'adaptive'],
              'max_iter' :[100, 150]
             }


mlp_random = RandomizedSearchCV(mlp,parameters,n_iter=15)
mlp_random.fit(y_train, y_train)
grid_parm=mlp_random.best_params_
print(grid_parm)

#Using the parameters obtained from HyperParameterTuning in the MLPClassifier
mlp = MLPClassifier(**grid_parm)
mlp.fit(X_train,y_train)
mlp_predict = mlp.predict(y_test)

#Obtain accuracy ,confusion matrix,classification report and AUC values for the result above.
print("accuracy Score (training) after hypertuning for MultiLayer Perceptron:{0:6f}".format(mlp.score(X_test,y_test)))
print("Confusion Matrix after hypertuning for MultiLayer Perceptron")
print(confusion_matrix(y_test,mlp_predict))
print("=== Classification Report ===")
print(classification_report(y_test,mlp_predict))

#get cross-validation report
mlp_cv_score = cross_val_score(mlp, X_train, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(mlp_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - MultiLayer Perceptron: ",mlp_cv_score.mean())


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:305: UserWarning: The total space of parameters 8 is smaller than n_iter=15. Running 8 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:693: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:693: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:693: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:693: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")
/usr/local/lib/python3

{'max_iter': 100, 'learning_rate': 'constant', 'activation': 'relu'}
accuracy Score (training) after hypertuning for MultiLayer Perceptron:0.753374
Confusion Matrix after hypertuning for MultiLayer Perceptron
[[15821    70]
 [ 7734  8018]]
=== Classification Report ===
              precision    recall  f1-score   support

           0       0.67      1.00      0.80     15891
           1       0.99      0.51      0.67     15752

    accuracy                           0.75     31643
   macro avg       0.83      0.75      0.74     31643
weighted avg       0.83      0.75      0.74     31643



/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:693: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:693: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:693: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


=== All AUC Scores ===
[0.95025162 0.93214423 0.94323894 0.96450096 0.96285902 0.96499986
 0.94764873 0.53974616 0.6448349  0.71806793]


=== Mean AUC Score ===
Mean AUC Score - MultiLayer Perceptron:  0.8568292345703487


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:693: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


## Meta Model - SVC

In [ ]:
model = SVC()

model = model.fit(S_Train, y_res)
y_pred = model.predict(S_Test)
print('Final prediction score for ensemble methods: [%.8f]' % accuracy_score(y_test, y_pred))
print(classification_report(y_pred, y_test))

In [ ]:
#Hyperparameter tuning done for SVC classifier

parameters = {'kernel':['linear', 'poly', 'rbf', 'sigmoid']}


svc_random = RandomizedSearchCV(svm,parameters,n_iter=15)
svc_random.fit(X_train, y_train)
grid_parm=svc_random.best_params_
print(grid_parm)

#Using the parameters obtained from HyperParameterTuning in the SVCClassifier
svc = SVC(**grid_parm)
svc.fit(X_train,y_train)
svc_predict = svc.predict(X_test)

#Obtain accuracy ,confusion matrix,classification report and AUC values for the result above.
print("accuracy Score (training) after hypertuning for MultiLayer Perceptron:{0:6f}".format(svc.score(X_test,y_test)))
print("Confusion Matrix after hypertuning for MultiLayer Perceptron")
print(confusion_matrix(y_test,svc_predict))
print("=== Classification Report ===")
print(classification_report(y_test,svc_predict))

#get cross-validation report
svc_cv_score = cross_val_score(svc, X_train, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(svc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - SVC: ",svc_cv_score.mean())

## Meta Model - Decision Tree

In [ ]:
model = DecisionTreeClassifier()
model = model.fit(S_Train, y_train)
y_pred = model.predict(S_Test)
print('Final prediction score for ensemble methods: [%.8f]' % accuracy_score(y_test, y_pred))
print('Classification report:')
print(classification_report(y_pred, y_test))
print('Maximum depth of the tree:')
print(model.tree_.max_depth)

Final prediction score for ensemble methods: [0.94248333]
Classification report:
              precision    recall  f1-score   support

           0       0.98      0.91      0.94     16985
           1       0.91      0.98      0.94     14658

    accuracy                           0.94     31643
   macro avg       0.94      0.94      0.94     31643
weighted avg       0.94      0.94      0.94     31643

Maximum depth of the tree:
5


In [ ]:
#Hyperparameter tuning done for decision tree classifier

parameters={'min_samples_split' : range(10,100,10),
            'max_depth': range(1,10,2),
            'criterion':['gini','entropy']
           }
clf_random = RandomizedSearchCV(model,parameters,n_iter=15)
clf_random.fit(X_train, y_train)
grid_parm=clf_random.best_params_
print(grid_parm)

#Using the parameters obtained from HyperParameterTuning in the DecisionTreeClassifier
clf = DecisionTreeClassifier(**grid_parm)
clf.fit(X_train, y_train)
clf_predict = clf.predict(X_test)

#Obtain accuracy ,confusion matrix,classification report and AUC values for the result above.
print("accuracy Score (training) after hypertuning for Decision Tree:{0:6f}".format(clf.score(X_test,y_test)))
print("Confusion Matrix after hypertuning for Decision Tree")
print(confusion_matrix(y_test,clf_predict))
print("=== Classification Report ===")
print(classification_report(y_test,clf_predict))

#get cross-validation report
clf_cv_score = cross_val_score(clf, X_train, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(clf_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Decision Tree: ",clf_cv_score.mean())

{'min_samples_split': 30, 'max_depth': 9, 'criterion': 'gini'}
accuracy Score (training) after hypertuning for Decision Tree:0.921341
Confusion Matrix after hypertuning for Decision Tree
[[14741  1150]
 [ 1339 14413]]
=== Classification Report ===
              precision    recall  f1-score   support

           0       0.92      0.93      0.92     15891
           1       0.93      0.91      0.92     15752

    accuracy                           0.92     31643
   macro avg       0.92      0.92      0.92     31643
weighted avg       0.92      0.92      0.92     31643

=== All AUC Scores ===
[0.98035517 0.97828666 0.97962921 0.98080839 0.97828688 0.97720437
 0.97871353 0.97809713 0.98137339 0.97937058]


=== Mean AUC Score ===
Mean AUC Score - Decision Tree:  0.9792125312885676


## Meta Model - Random Forest

In [ ]:
model = RandomForestClassifier()
model = model.fit(S_Train, y_train)
y_pred = model.predict(S_Test)
print('Final prediction score for ensemble methods: [%.8f]' % accuracy_score(y_test, y_pred))
print('Classification report:')
print(classification_report(y_pred, y_test))

Final prediction score for ensemble methods: [0.94248333]
Classification report:
              precision    recall  f1-score   support

           0       0.98      0.91      0.94     16985
           1       0.91      0.98      0.94     14658

    accuracy                           0.94     31643
   macro avg       0.94      0.94      0.94     31643
weighted avg       0.94      0.94      0.94     31643



In [ ]:
#Hyperparameter tuning for random forest classifier
rfc_random = RandomizedSearchCV(model,parameters,n_iter=15)
rfc_random.fit(X_train, y_train)
grid_parm_rfc=rfc_random.best_params_
print(grid_parm_rfc)

#Construct Random Forest with best parameters
rfc= RandomForestClassifier(**grid_parm_rfc)
rfc.fit(X_train,y_train)
rfc_predict = rfc.predict(X_test)
print("accuracy Score (training) after hypertuning for Random Forest:{0:6f}".format(rfc.score(X_test,y_test)))
print("Confusion Matrix after hypertuning for Random Forest:")
print(confusion_matrix(y_test,rfc_predict))
print("=== Classification Report ===")
print(classification_report(y_test,rfc_predict))

#get cross-validation report
rfc_cv_score = cross_val_score(rfc, X_train, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(rfc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ",rfc_cv_score.mean())

{'min_samples_split': 30, 'max_depth': 9, 'criterion': 'entropy'}
accuracy Score (training) after hypertuning for Random Forest:0.912208
Confusion Matrix after hypertuning for Random Forest:
[[14230  1661]
 [ 1117 14635]]
=== Classification Report ===
              precision    recall  f1-score   support

           0       0.93      0.90      0.91     15891
           1       0.90      0.93      0.91     15752

    accuracy                           0.91     31643
   macro avg       0.91      0.91      0.91     31643
weighted avg       0.91      0.91      0.91     31643



KeyboardInterrupt: ignored

## Meta Model - KNN

In [ ]:
model = KNeighborsClassifier()
model = model.fit(S_Train, y_train)
y_pred = model.predict(S_Test)
print('Final prediction score for ensemble methods: [%.8f]' % accuracy_score(y_test, y_pred))
print('Classification report:')
print(classification_report(y_pred, y_test))

Final prediction score for ensemble methods: [0.94317859]
Classification report:
              precision    recall  f1-score   support

           0       0.97      0.92      0.95     16855
           1       0.91      0.97      0.94     14788

    accuracy                           0.94     31643
   macro avg       0.94      0.94      0.94     31643
weighted avg       0.95      0.94      0.94     31643



In [ ]:
#Hyperparameter tuning done for K-Nearest Neighbor classifier

parameters = {'n_neighbors':[3,5,7], 'weights':['uniform', 'distance']}


neigh_random = RandomizedSearchCV(model,parameters,n_iter=15)
neigh_random.fit(X_train, y_train)
grid_parm=neigh_random.best_params_
print(grid_parm)

#Using the parameters obtained from HyperParameterTuning in the MLPClassifier
neigh = KNeighborsClassifier(**grid_parm)
neigh.fit(X_train,y_train)
neigh_predict = neigh.predict(X_test)

#Obtain accuracy ,confusion matrix,classification report and AUC values for the result above.
print("accuracy Score (training) after hypertuning for KNeighborsClassifier:{0:6f}".format(neigh.score(X_test,y_test)))
print("Confusion Matrix after hypertuning for KNeighborsClassifier")
print(confusion_matrix(y_test,neigh_predict))
print("=== Classification Report ===")
print(classification_report(y_test,neigh_predict))

#get cross-validation report
neigh_cv_score = cross_val_score(neigh, X_train, y_train, cv=10, scoring="roc_auc")
print("=== All AUC Scores ===")
print(neigh_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - KNeighborsClassifier: ",neigh_cv_score.mean())

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:305: UserWarning: The total space of parameters 6 is smaller than n_iter=15. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


{'weights': 'distance', 'n_neighbors': 3}


KeyboardInterrupt: ignored

## Training on the entire dataset with only those models that performed good and getting predictions for kaggle testing dataset

### Individual Decision Tree

In [ ]:
clf = DecisionTreeClassifier()
clf.fit(X_res,y_res)
clf_predict=clf.predict(X_test)
clf_predict_prob = clf.predict_proba(test_data)
np.savetxt("dt_k.csv", clf_predict_prob, delimiter=",")

In [ ]:
clf_predict_prob

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [ ]:
test_data['QuoteNumber']

0              3
1              5
2              7
3              9
4             10
           ...  
173831    434570
173832    434573
173833    434574
173834    434575
173835    434589
Name: QuoteNumber, Length: 173836, dtype: int64

In [ ]:
dt_kaggle = pd.DataFrame({'QuoteNumber':test_data['QuoteNumber'], 'QuoteConversion_Flag':clf_predict_prob[:,1]})
dt_kaggle

QuoteNumber  QuoteConversion_Flag
0                 3                   0.0
1                 5                   0.0
2                 7                   0.0
3                 9                   0.0
4                10                   1.0
...             ...                   ...
173831       434570                   0.0
173832       434573                   0.0
173833       434574                   1.0
173834       434575                   0.0
173835       434589                   1.0

[173836 rows x 2 columns]

In [ ]:
dt_kaggle.to_csv('dt_results.csv',index=False)

### Individual Random Forest model

In [ ]:
rfc = RandomForestClassifier()
rfc.fit(X_res, y_res)
rfc_predict=rfc.predict(X_test)
rfc_predict_prob = rfc.predict_proba(test_data)
np.savetxt("rfc_k.csv", rfc_predict_prob, delimiter=",")

print(rfc_predict_prob)

rf_kaggle = pd.DataFrame({'QuoteNumber':test_data['QuoteNumber'], 'QuoteConversion_Flag':rfc_predict_prob[:,1]})
rf_kaggle

[[0.91 0.09]
 [0.72 0.28]
 [0.73 0.27]
 ...
 [0.31 0.69]
 [0.91 0.09]
 [0.54 0.46]]


QuoteNumber  QuoteConversion_Flag
0                 3                  0.09
1                 5                  0.28
2                 7                  0.27
3                 9                  0.23
4                10                  0.30
...             ...                   ...
173831       434570                  0.25
173832       434573                  0.39
173833       434574                  0.69
173834       434575                  0.09
173835       434589                  0.46

[173836 rows x 2 columns]

In [ ]:
rf_kaggle.to_csv('rf_results.csv',index=False)

### Individual MLP model

In [ ]:
mlp = MLPClassifier(max_iter = 100)
mlp.fit(X_res, y_res)
mlp_predict=mlp.predict(test_data)
mlp_predict_prob = mlp.predict_proba(test_data)
np.savetxt("nn_k.csv", mlp_predict_prob, delimiter=",")

print(mlp_predict_prob)

mlp_kaggle = pd.DataFrame({'QuoteNumber':test_data['QuoteNumber'], 'QuoteConversion_Flag':mlp_predict_prob[:,1]})
mlp_kaggle

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


[[1.00000000e+00 2.66729579e-10]
 [9.99999891e-01 1.09198059e-07]
 [1.00000000e+00 8.80707478e-12]
 ...
 [1.00000000e+00 5.15926917e-45]
 [1.00000000e+00 2.20319141e-64]
 [1.00000000e+00 2.22937030e-58]]


QuoteNumber  QuoteConversion_Flag
0                 3          2.667296e-10
1                 5          1.091981e-07
2                 7          8.807075e-12
3                 9          1.094226e-08
4                10          8.596974e-11
...             ...                   ...
173831       434570          2.174657e-52
173832       434573          7.835911e-56
173833       434574          5.159269e-45
173834       434575          2.203191e-64
173835       434589          2.229370e-58

[173836 rows x 2 columns]

In [ ]:
mlp_kaggle.to_csv('mlp_results.csv',index=False)

### Individual KNN Model

In [ ]:
neigh = KNeighborsClassifier(n_neighbors=3)

neigh.fit(X_train, y_train)
neigh_predict=neigh.predict(X_test)

neigh_predict_prob = neigh.predict_proba(test_data)
np.savetxt("knn_k.csv", neigh_predict_prob, delimiter=",")

print(neigh_predict_prob)

neigh_kaggle = pd.DataFrame({'QuoteNumber':test_data['QuoteNumber'], 'QuoteConversion_Flag':neigh_predict_prob[:,1]})
neigh_kaggle

[[0.66666667 0.33333333]
 [0.33333333 0.66666667]
 [0.33333333 0.66666667]
 ...
 [1.         0.        ]
 [0.33333333 0.66666667]
 [1.         0.        ]]


QuoteNumber  QuoteConversion_Flag
0                 3              0.333333
1                 5              0.666667
2                 7              0.666667
3                 9              0.000000
4                10              0.666667
...             ...                   ...
173831       434570              0.000000
173832       434573              0.000000
173833       434574              0.000000
173834       434575              0.666667
173835       434589              0.000000

[173836 rows x 2 columns]

In [ ]:
neigh_kaggle.to_csv('neigh_results.csv',index=False)

When we look at the kaggle scores, neural network does not perform very well because the size of our dataset has increased significantly. training neural networks efficiently on larger datasets require GPU's and TPU's, which we do not have access to. This can degrade the performance of the model.

We already know KNN's do not work well for large datasets with large features. So, it is not surprising that KNN gave the worst kaggle score.

We also know that Random forests perform well on large datasets with large features, so it received the highest kaggle score

### Stacking

In [ ]:
models = [ MLPClassifier(max_iter = 100), SVC(max_iter = 500, probability = True), DecisionTreeClassifier(), RandomForestClassifier(), KNeighborsClassifier(n_neighbors=3)]

S_Train, S_Test = stacking(models,
                           X_res, y_res, test_data,
                           regression=False,

                           mode='oof_pred_bag',

                           needs_proba= True,

                           save_dir=None,

                           metric=log_loss,

                           n_folds=4,

                           stratified=True,

                           shuffle=True,

                           random_state=0,

                           verbose=2)

task:         [classification]
n_classes:    [2]
metric:       [log_loss]
mode:         [oof_pred_bag]
n_models:     [5]

model  0:     [MLPClassifier]
    fold  0:  [9.03050973]
    fold  1:  [2.27835436]
    fold  2:  [9.14707393]
    fold  3:  [0.95618105]
    ----
    MEAN:     [5.35302977] + [3.76512076]
    FULL:     [5.35302977]

model  1:     [SVC]


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


    fold  0:  [0.69315966]


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


    fold  1:  [0.69314718]


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


    fold  2:  [0.69314718]


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


    fold  3:  [0.69317944]
    ----
    MEAN:     [0.69315837] + [0.00001319]
    FULL:     [0.69315837]

model  2:     [DecisionTreeClassifier]
    fold  0:  [2.90191802]
    fold  1:  [2.87184633]
    fold  2:  [2.85270980]
    fold  3:  [2.85407669]
    ----
    MEAN:     [2.87013771] + [0.01984059]
    FULL:     [2.87013771]

model  3:     [RandomForestClassifier]
    fold  0:  [0.17286627]
    fold  1:  [0.17118742]
    fold  2:  [0.17109037]
    fold  3:  [0.17411780]
    ----
    MEAN:     [0.17231546] + [0.00125749]
    FULL:     [0.17231546]

model  4:     [KNeighborsClassifier]
    fold  0:  [3.22093603]
    fold  1:  [3.28344950]
    fold  2:  [3.25059892]
    fold  3:  [3.26211823]
    ----
    MEAN:     [3.25427567] + [0.02257027]
    FULL:     [3.25427567]



In [ ]:
S_Test

array([[0.50000664, 0.49999336, 0.49833815, ..., 0.0975    , 0.83333333,
        0.16666667],
       [0.88713876, 0.11286124, 0.5       , ..., 0.235     , 0.5       ,
        0.5       ],
       [0.50000138, 0.49999862, 0.49831519, ..., 0.23      , 0.75      ,
        0.25      ],
       ...,
       [0.5       , 0.5       , 0.5       , ..., 0.6925    , 1.        ,
        0.        ],
       [0.5       , 0.5       , 0.5       , ..., 0.125     , 0.5       ,
        0.5       ],
       [0.5       , 0.5       , 0.5       , ..., 0.4825    , 1.        ,
        0.        ]])

In [ ]:

np.savetxt("s_stacking_train.csv", S_Train, delimiter=",")

In [ ]:
np.savetxt("s_stacking_test.csv", S_Test, delimiter=",")

### Meta Model - Decision Tree

In [ ]:
model = DecisionTreeClassifier()

model = model.fit(S_Train, y_res)
y_pred = model.predict(S_Test)
y_pred_proba = model.predict_proba(S_Test)

In [ ]:
y_pred_proba

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [ ]:
dt_stacking_kaggle = pd.DataFrame({'QuoteNumber':test_data['QuoteNumber'], 'QuoteConversion_Flag':y_pred_proba[:,1]})
dt_stacking_kaggle

QuoteNumber  QuoteConversion_Flag
0                 3                   0.0
1                 5                   0.0
2                 7                   0.0
3                 9                   0.0
4                10                   1.0
...             ...                   ...
173831       434570                   0.0
173832       434573                   0.0
173833       434574                   0.0
173834       434575                   1.0
173835       434589                   0.0

[173836 rows x 2 columns]

In [ ]:
dt_stacking_kaggle.to_csv('dt_stacking_results.csv',index=False)

### Meta Model - Random Forest

In [ ]:
model = RandomForestClassifier()

model = model.fit(S_Train, y_res)
y_pred = model.predict(S_Test)
y_pred_proba = model.predict_proba(S_Test)

rfc_stacking_kaggle = pd.DataFrame({'QuoteNumber':test_data['QuoteNumber'], 'QuoteConversion_Flag':y_pred_proba[:,1]})
rfc_stacking_kaggle

QuoteNumber  QuoteConversion_Flag
0                 3                  0.01
1                 5                  0.01
2                 7                  0.18
3                 9                  0.00
4                10                  0.47
...             ...                   ...
173831       434570                  0.00
173832       434573                  0.00
173833       434574                  0.16
173834       434575                  0.07
173835       434589                  0.01

[173836 rows x 2 columns]

In [ ]:
rfc_stacking_kaggle.to_csv('rfc_stacking_results.csv',index=False)

### Meta Model - MLP model

In [ ]:
model = MLPClassifier(max_iter = 100)

model = model.fit(S_Train, y_res)
y_pred = model.predict(S_Test)

y_pred_proba = model.predict_proba(S_Test)

mlp_stacking_kaggle = pd.DataFrame({'QuoteNumber':test_data['QuoteNumber'], 'QuoteConversion_Flag':y_pred_proba[:,1]})
mlp_stacking_kaggle

QuoteNumber  QuoteConversion_Flag
0                 3              0.007216
1                 5              0.116864
2                 7              0.055806
3                 9              0.010229
4                10              0.195145
...             ...                   ...
173831       434570              0.057289
173832       434573              0.041104
173833       434574              0.470741
173834       434575              0.041626
173835       434589              0.072990

[173836 rows x 2 columns]

In [ ]:
mlp_stacking_kaggle.to_csv('mlp_stacking_results.csv',index=False)

### Meta Model - SVC

In [ ]:
model = SVC(max_iter = 500, probability = True)

model = model.fit(S_Train, y_res)
y_pred = model.predict(S_Test)

y_pred_proba = model.predict_proba(S_Test)

svc_stacking_kaggle = pd.DataFrame({'QuoteNumber':test_data['QuoteNumber'], 'QuoteConversion_Flag':y_pred_proba[:,1]})
svc_stacking_kaggle

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=500).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


QuoteNumber  QuoteConversion_Flag
0                 3              0.026735
1                 5              0.126200
2                 7              0.148883
3                 9              0.006120
4                10              0.692111
...             ...                   ...
173831       434570              0.052913
173832       434573              0.097628
173833       434574              0.027988
173834       434575              0.223149
173835       434589              0.113826

[173836 rows x 2 columns]

In [ ]:
svc_stacking_kaggle.to_csv('svc_stacking_results.csv',index=False)

### Meta Model - KNN

In [ ]:
model = KNeighborsClassifier(n_neighbors = 3)

model = model.fit(S_Train, y_res)
y_pred = model.predict(S_Test)

y_pred_proba = model.predict_proba(S_Test)

knn_stacking_kaggle = pd.DataFrame({'QuoteNumber':test_data['QuoteNumber'], 'QuoteConversion_Flag':y_pred_proba[:,1]})
knn_stacking_kaggle

QuoteNumber  QuoteConversion_Flag
0                 3              0.000000
1                 5              0.000000
2                 7              0.000000
3                 9              0.000000
4                10              0.333333
...             ...                   ...
173831       434570              0.000000
173832       434573              0.000000
173833       434574              0.333333
173834       434575              0.333333
173835       434589              0.000000

[173836 rows x 2 columns]

In [ ]:
knn_stacking_kaggle.to_csv('knn_stacking_results.csv',index=False)